name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh-staging
          server-username: ${{ env.SONATYPE_USERNAME }}
          server-password: ${{ env.SONATYPE_PASSWORD }}
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy -Dgpg.passphrase=${{ env.GPG_PASSPHRASE }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}